### ISSUE TITLE
Some extra advices/comments

### ISSUE THREAD

**Issue by luongvo** [cuonghuynhvan/nimble-surveys#11]
- Be consistent in using camel case or snake case when naming variables, function names...
- Kotlin Flavor: scoping functions e.g let, run, apply..., extension functions, safety nullable access, synthetic... to optimize and deliver better code.
- Enable proguard as soon as you can to avoid last-minute panic when enabling them for production/release flavor.
- If you could have a small UI test with instrumentation setup and simple test cases that would be a plus, but perhaps not mandatory for now given the time constraint of the project.

Any questions do feel free to bump it up, happy coding 👨‍🎤

**Comment by cuonghuynhvan** [comment]
Thank for your advice @luongvo 

I have added some Android test for the login screen here #14
