### ISSUE TITLE
Some first ui issues

### ISSUE THREAD

**Issue by luongvo** [cuonghuynhvan/nimble-surveys#7]
Hi @cuonghuynhvan, I'm Lucas from Nimble. Nice to meet you here 👋 

I'll take care of reviewing your assignment and give you some feedback here from our side by opening issue tickets. Please feel free to catch up on this and help us know more about you by discussing and resolving the issues.

Firstly, you're doing well, the build is running smoothly and has a nice ui 👌 
However, there are just some extra ui issues we should take a look at:
- Password validation on the `Login screen`: it does seem a bit annoying to the user when typing the password with the error popping up on the right side. The error popup doesn't seem to be good for live-validation, how do you think?
![20201127_112630](https://user-images.githubusercontent.com/16315358/100423986-83059500-30bf-11eb-82e1-7d5f3a074335.gif)

- On the main survey list screen, there is a `Today` label that should be adapted to the date label above as the day of week.
![image](https://user-images.githubusercontent.com/16315358/100424484-3ff7f180-30c0-11eb-9265-70702dbd54e0.png)

- Also on this screen, let's imagine the user avatar doesn't belong to the survey content so it should not be located on the survey layout but fixed on screen when navigating between survey items. This is quite an extra UI/UX thinking on app layouting.
![image](https://user-images.githubusercontent.com/16315358/100424461-3a021080-30c0-11eb-9102-96a2a224fe64.png)

**Comment by cuonghuynhvan** [comment]
Hi @luongvo, 
Nice to meet you too.

```
Password validation on the Login screen: it does seem a bit annoying to the user when typing the password with the error popping up on the right side. The error popup doesn't seem to be good for live-validation, how do you think?
```
You are right, I've removed the live-validate. The validation is now triggered when the user clicks login. button.

```
On the main survey list screen, there is a Today label that should be adapted to the date label above as the day of week.
```
So, I don't have the clear requirement here, so I changed it from 
<img width="212" alt="Screen Shot 2020-11-29 at 16 16 35" src="https://user-images.githubusercontent.com/7866660/100538043-ed553b80-325f-11eb-9af9-98421b323506.png">
to
<img width="256" alt="Screen Shot 2020-11-29 at 16 18 31" src="https://user-images.githubusercontent.com/7866660/100538045-f0e8c280-325f-11eb-89dd-2e1eb27b082b.png">

```
Also on this screen, let's imagine the user avatar doesn't belong to the survey content so it should not be located on the survey layout but fixed on screen when navigating between survey items. This is quite an extra UI/UX thinking on app layouting.
```
It's done.

Please check my PR here #12

**Comment by luongvo** [comment]
@cuonghuynhvan sometimes I got this crash when starting/resuming the app after a long-unused time
```
2020-12-02 14:41:15.637 31790-31892/com.nimble.survey E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.nimble.survey, PID: 31790
    java.lang.NullPointerException
        at com.nimble.survey.data.api.AuthenticationHeaderInterceptor.refreshToken(APIBuilder.kt:83)
        at com.nimble.survey.data.api.AuthenticationHeaderInterceptor.intercept(APIBuilder.kt:59)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
